Frontend MVC/Controllers/PlatosController.cs
using System;
using System.Text;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Frontend_MVC.Models;
using Frontend_MVC.Models.ViewModels;
using Frontend_MVC.Services;

namespace Frontend_MVC.Controllers
{
    public class PlatosController : Controller
    {
        private readonly IService _iservice;


        public PlatosController(IService iservice)
        {
            _iservice = iservice;
        }

        // GET: PlatosController
        public async Task<ActionResult> Index()
        {
            List<PlatosModel> platos = await _iservice.GetPlatos();

            List<PlatosViewModel> platosView = mapearViewPlato(platos);

            return View(platosView);
        }

        // GET: PlatosController/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.Categorias = await GetCategorias();
            return View();
        }

        // POST: PlatosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(PlatosViewModel plato)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    PlatosModel platoNuevo = new PlatosModel();

                    if (plato.ImagenSubida != null)
                    {
                        using (var ms = new MemoryStream())
                        {
                            plato.ImagenSubida.CopyTo(ms);
                            platoNuevo.Imagen = ms.ToArray();
                        }
                    }
                    
                    platoNuevo.Nombre = plato.Nombre;
                    platoNuevo.CategoriaId = plato.CategoriaId;
                    platoNuevo.Descripcion = plato.Descripcion;
                    platoNuevo.Precio = plato.Precio;

                    await _iservice.PostPlatos(platoNuevo);
                    return RedirectToAction(nameof(Index));

                }
                catch
                {
                    ViewBag.Categorias = await GetCategorias();
                    return View();
                }
            }
            ViewBag.Categorias = await GetCategorias();
            return View();
        }

        // GET: PlatosController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var plato = await _iservice.GetPlatoPorID(id);

            List<PlatosViewModel> platosView = mapearViewPlato(new List<PlatosModel> { plato });

            return View(platosView.First());
        }

        // POST: PlatosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(PlatosModel plato)
        {
            try
            {
                await _iservice.PutPlatos(plato);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PlatosController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var plato = await _iservice.GetPlatoPorID(id);

            List<PlatosViewModel> platosView = mapearViewPlato(new List<PlatosModel> { plato });

            return View(platosView.First());
        }

        // POST: PlatosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                await _iservice.DeletePlatos(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private List<PlatosViewModel> mapearViewPlato(List<PlatosModel> platos)
        {

            List<PlatosViewModel> platosAuxiliar = new List<PlatosViewModel>();

            foreach (PlatosModel plato in platos)
            {
                platosAuxiliar.Add(new PlatosViewModel
                {
                    Id = plato.Id,
                    Nombre = plato.Nombre,
                    Descripcion = plato.Descripcion,
                    Imagen = plato.Imagen,
                    Precio = plato.Precio,
                    CategoriaNombre = plato.Categoria.Nombre
                });
            }

            return platosAuxiliar;
        }


        private async Task<List<CategoriasModel>> GetCategorias()
        {
            List<CategoriasModel> categorias = await _iservice.GetCategorias();
            return categorias;
        }
    }

}

Frontend MVC/Controllers/ReportesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Frontend_MVC.Services;

namespace Frontend_MVC.Controllers
{
    public class ReportesController : Controller
    {
        private readonly IService _iservice;


        public ReportesController(IService iservice)
        {
            _iservice = iservice;
        }

        // GET: Reportes
        public async Task<IActionResult> IndexVentasDia()
        {
            ViewBag.Ventas = await _iservice.ObtenerVentasDia();
            return View("VentasDelDia");
        }

        // GET: Reportes/VentasDelDia/{fecha}
        public async Task<IActionResult> VentasDia(DateTime FechaDia)
        {
            ViewBag.Ventas = await _iservice.ObtenerVentasDia(FechaDia);
            return View("VentasDelDia");
        }

        // GET: Reportes
        public async Task<IActionResult> IndexVentasMes()
        {
            ViewBag.Ventas = await _iservice.ObtenerVentasMes();
            return View("VentasDelMes");
        }

        // GET: Reportes/VentasDelDia/{fecha}
        public async Task<IActionResult> VentasMes(DateTime FechaMes)
        {
            ViewBag.Ventas = await _iservice.ObtenerVentasMes(FechaMes);
            return View("VentasDelMes");
        }

        // GET: Reportes
        public async Task<IActionResult> IndexVentasRango()
        {
            ViewBag.Ventas = await _iservice.ObtenerVentasRango();
            return View("VentasEnUnRango");
        }

        // GET: Reportes/VentasDelDia/{fecha}
        public async Task<IActionResult> VentasRango(DateTime FechaInicio, DateTime FechaFin)
        {
            ViewBag.Ventas = await _iservice.ObtenerVentasRango(FechaInicio, FechaFin);
            return View("VentasEnUnRango");

        }

        // GET: Reportes
        public async Task<IActionResult> IndexPlatoMasVendidoDelMes()
        {
            ViewBag.Plato = await _iservice.ObtenerPlatoMasVendidoDelMes();
            return View("PlatoMasVendidoMes");
        }

        // GET: Reportes
        public async Task<IActionResult> PlatoMasVendidoDelMes(DateTime FechaMes)
        {
            ViewBag.Plato = await _iservice.ObtenerPlatoMasVendidoDelMes(FechaMes);
            return View("PlatoMasVendidoMes");
        }

    }
}

Frontend MVC/Controllers/ReservasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Frontend_MVC.Models;
using Frontend_MVC.Models.ViewModels;
using Frontend_MVC.Services;

namespace Frontend_MVC.Controllers
{
    public class ReservasController : Controller
    {

        private readonly IService _iservice;


        public ReservasController(IService iservice)
        {
            _iservice = iservice;
        }

        // GET: ReservasController
        public async Task<IActionResult> Index()
        {
            List<ReservasViewModel> reservas = await _iservice.GetReservas();

            return View(reservas);
        }

        // GET: ReservasController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ReservasController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ReservasModel reserva)
        {
            try
            {
                await _iservice.PostReservas(reserva);
                return RedirectToAction(nameof(Index));

            }
            catch
            {
                return View();
            }
        }

        // GET: ReservasController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var reserva = await _iservice.GetReservaPorID(id);

            return View(reserva);
        }

        // POST: ReservasController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ReservasModel reserva)
        {
            try
            {
                await _iservice.PutReservas(reserva);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ReservasController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var reserva = await _iservice.GetReservaPorID(id);

            return View(reserva);
        }

        // POST: ReservasController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                await _iservice.DeleteReservas(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Frontend MVC/Controllers/VentasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Frontend_MVC.Models;
using Frontend_MVC.Models.ViewModels;
using Frontend_MVC.Services;

namespace Frontend_MVC.Controllers
{
    public class VentasController : Controller
    {
        //private readonly IMemoryCache _cache;
        private readonly IService _iservice;


        public VentasController(/*IMemoryCache cache*/IService iservice)
        {
            //_cache = cache;
            _iservice = iservice;
        }

        // GET: VentasController
        public async Task<ActionResult> Index()
        {
            List<VentasModel> ventas = await _iservice.GetVentas();

            List<VentasViewModel> ventasView = MapearViewVenta(ventas);

            return View(ventasView);
        }

        // GET: VentasController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: VentasController/Create
        public async Task<IActionResult> Create()
        {
            List<PlatosModel> platos = await _iservice.GetPlatos();
            ViewBag.Platos = platos;
            return View();
        }

        // POST: VentasController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(VentasModel Venta)
        {
            try
            {
                await _iservice.PostVentas(Venta);
                return RedirectToAction(nameof(Index));

            }
            catch
            {
                return View();
            }
        }

        // GET: VentasController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var venta = await _iservice.GetVentaPorID(id);

            List<VentasViewModel> ventasView = MapearViewVenta(new List<VentasModel> { venta });

            return View(ventasView.First());
        }

        // POST: VentasController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(VentasModel Venta)
        {
            try
            {
                await _iservice.PutVentas(Venta);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VentasController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var venta = await _iservice.GetVentaPorID(id);
           
            List<VentasViewModel> ventasView = MapearViewVenta(new List<VentasModel> { venta });

            return View(ventasView.First());
        }

        // POST: VentasController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                await _iservice.DeleteVentas(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private List<VentasViewModel> MapearViewVenta(List<VentasModel> ventas) {

            List<VentasViewModel> ventasAuxiliar = new List<VentasViewModel>();

            foreach(VentasModel venta in ventas) {
                ventasAuxiliar.Add(new VentasViewModel
                {
                    NumeroOrden = venta.NumeroOrden,
                    CantidadVendida = venta.CantidadVendida,
                    FechaHora = venta.FechaHora,
                    Plato = venta.Plato.Nombre
                });
            };
            return ventasAuxiliar;
        }
    }

}

Frontend MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proyecto Restaurante</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body class="body position-relative min-vh-100">
    <header>
        <nav class="navbar nav-pills navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Platos" asp-action="Index">Proyecto Restaurante</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Platos" asp-action="Index">Platos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ventas" asp-action="Index">Ventas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservas" asp-action="Index">Reservaciones</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Reportes
                            </a>
                            <ul class="dropdown-menu">
                                <li> <a class="dropdown-item" asp-area="" asp-controller="Reportes" asp-action="IndexVentasDia">Ventas del día</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Reportes" asp-action="IndexVentasMes">Ventas del mes</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Reportes" asp-action="IndexVentasRango">Ventas en un rango</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-area="" asp-controller="Reportes" asp-action="IndexPlatoMasVendidoDelMes">Plato más vendido del mes</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="main-container container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bottom-0 position-absolute w-100">
        <div class="container d-flex flex-column align-items-center">
            <p>&copy; 2023 - Proyecto Restaurante</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>